services:
  - type: web
    name: maritime-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: ./start.sh
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DJANGO_DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: maritime-db
          property: connectionString
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
      - key: DJANGO_CORS_ALLOWED_ORIGINS
        sync: false
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        sync: false

databases:
  - name: maritime-db
    plan: free
    databaseName: maritime_db
    user: maritime_user
